curator announcer
medallia/linkerd pull request #1
Opened 2016-09-27 07:59 UTC by erdody

* Added ability to announce to ZK with medallia's curator format
* Updated Announcer to be closeable so we can gracefully close ZK connections

2016-09-29 21:48 UTC, AbhiMedallia requested changes

2016-09-29 21:48 UTC, AbhiMedallia commented on linkerd/announcer/curatorsd/src/main/scala/io/buoyant/linkerd/announcer/curatorsd/CuratorSDAnnouncer.scala
> +        val parts: Array[String] = serviceDef.split("#")
I think it is better to create a regex here. Will make it easier to understand/validate
whether the string is correct and also parse it.

2016-09-29 21:48 UTC, AbhiMedallia commented on linkerd/announcer/curatorsd/src/main/scala/io/buoyant/linkerd/announcer/curatorsd/CuratorSDAnnouncer.scala
> +  private val curatorClient = CuratorFrameworkFactory.builder
I am not sure how curator handles disconnection from zookeeper. If it is disconnected from zookeeper can you still use stale routing data in your client.

2016-09-29 21:48 UTC, AbhiMedallia commented on linkerd/announcer/curatorsd/src/main/scala/io/buoyant/linkerd/announcer/curatorsd/CuratorSDAnnouncerInitializer.scala
> +  override def defaultPrefix: Path = Path.read("/io.l5d.curatorsd")
Is this the zookeeper path which is used by curator as the base directory?

2016-09-30 05:23 UTC, erdody commented on linkerd/announcer/curatorsd/src/main/scala/io/buoyant/linkerd/announcer/curatorsd/CuratorSDAnnouncerInitializer.scala
> +  override def defaultPrefix: Path = Path.read("/io.l5d.curatorsd")
No, this is the linkerd config id for the announcer (explained in the javadoc).
The base path (chroot) can be specified in the zkConnectStr.

2016-09-30 05:24 UTC, erdody commented on linkerd/announcer/curatorsd/src/main/scala/io/buoyant/linkerd/announcer/curatorsd/CuratorSDAnnouncer.scala
> +  private val curatorClient = CuratorFrameworkFactory.builder
ZK Reconnection is transparently handled by the curator client.

2016-09-30 17:59 UTC, erdody commented on linkerd/announcer/curatorsd/src/main/scala/io/buoyant/linkerd/announcer/curatorsd/CuratorSDAnnouncer.scala
> +        val parts: Array[String] = serviceDef.split("#")
I'll handle this in the next case that is based on this branch (RA-1371)

2016-09-30 18:01 UTC, merged